name: wxread

on:
  schedule:
    # 凌晨任务：北京时间每天 01:00（UTC 前一天 17:00）
    #- cron: '0 17 * * *'
    # 早间任务：北京时间每天 07:00（UTC 前一天 23:00）
    - cron: '0 23 * * *'
    # 午间任务：北京时间每天 11:40（UTC 03:40）
    #- cron: '40 3 * * *'
    # 晚间任务：北京时间每天 22:00（UTC 14:00）
    #- cron: '0 14 * * *'
  workflow_dispatch:  # 手动触发

jobs:
  wxread_1:
    uses: ./.github/workflows/reusable-deploy.yml
    secrets:
      WXREAD_CURL_BASH: ${{ secrets.WXREAD_CURL_BASH_1 }}
      PUSH_METHOD: ${{ secrets.PUSH_METHOD }}
      PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      WXPUSHER_SPT: ${{ secrets.WXPUSHER_SPT }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

  wxread_2:
    needs: wxread_1
    uses: ./.github/workflows/reusable-deploy.yml
    secrets:
      WXREAD_CURL_BASH: ${{ secrets.WXREAD_CURL_BASH_2 }}
      PUSH_METHOD: ${{ secrets.PUSH_METHOD }}
      PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      WXPUSHER_SPT: ${{ secrets.WXPUSHER_SPT }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
